### ISSUE TITLE
Errors from frun with Wasi 6/7

### ISSUE THREAD

**Issue by touhonoob** [fluencelabs/c-backend-sdk#1]
Hi guys, Is the CPP SDK uptodate?
I tried to test it locally with frun getting following errors:
```shell
> docker run --rm -v $(pwd)/fluence_libvips.wasm:/code/code.wasm -p 30000:30000 fluencelabs/frun:latest
2019-10-07 18:10:14 info  run:    WasmVm: configs read...
fluence.vm.VmError$InitializationError: Preparing execution context before execution was failed for NonEmptyList(/code/code.wasm).
Caused by: java.lang.Exception: Failed loading /code/code.wasm - List is empty.
    at asmble.cli.ScriptCommand.prepareContext(ScriptCommand.kt:85)
    at fluence.vm.WasmVm$.prepareContext(WasmVm.scala:151)
    at fluence.vm.WasmVm$.$anonfun$apply$4(WasmVm.scala:108)
    at scala.util.Try$.apply(Try.scala:213)
    at fluence.vm.utils$.safelyRunThrowable(utils.scala:35)
    at fluence.vm.WasmVm$.$anonfun$apply$3(WasmVm.scala:107)
    at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
    at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
    at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.NoSuchElementException: List is empty.
    at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:347)
    at asmble.io.BinaryToAst.toModule(BinaryToAst.kt:217)
    at asmble.cli.Translate.inToAst(Translate.kt:73)
    at asmble.cli.ScriptCommand.prepareContext(ScriptCommand.kt:70)
    ... 16 more
```

main.cpp
```cpp
#include "fluence-sdk/cpp_sdk/logger.h"
#include "fluence-sdk/cpp_sdk/allocator.h"
#include <string.h>

const char *const greeting = "Hello world! From ";
const int RESPONSE_SIZE_BYTES = 4;

extern "C" char *invoke(const char *str, int length) {
    const size_t greeting_length = strlen(greeting);
    const size_t response_length = length + greeting_length;

    char *response = (char *)sdk::allocate(response_length + RESPONSE_SIZE_BYTES);

    sdk::wasm_log(str);

    // (1)
    for(int i = 0; i < RESPONSE_SIZE_BYTES; ++i) {
        response[i] = (response_length >> 8*i) & 0xFF;
    }

    // (2)
    memcpy(response + RESPONSE_SIZE_BYTES, greeting, greeting_length);
    memcpy(response + RESPONSE_SIZE_BYTES + greeting_length, str, length);

    return response;
}
```

Makefile
```
TARGET = fluence_libvips
CC = /opt/wasi-sdk/bin/clang++
SYSROOT = /opt/wasi-sdk/share/wasi-sysroot
TARGET_TRIPLE = wasm32-unknown-wasi
CFLAGS = -nostartfiles -fvisibility=hidden
LDFLAGS = -Wl,--no-entry,--demangle,--allow-undefined
EXPORT_FUNCS = --export=allocate,--export=deallocate,--export=invoke
SDK = fluence-sdk/cpp_sdk/allocator.cpp fluence-sdk/cpp_sdk/logger.cpp

.PHONY: default all clean

default: $(TARGET)
all: default

$(TARGET): main.cpp $(SDK)
	$(CC) --sysroot=$(SYSROOT) --target=$(TARGET_TRIPLE) $(CFLAGS) $(LDFLAGS) -Wl,$(EXPORT_FUNCS) $^ -o $@.wasm

.PRECIOUS: $(TARGET)

clean:
	-rm -f $(TARGET).wasm
```

**Comment by touhonoob** [comment]
Getting a different error after downgrading to Wasi 6
```
> docker run --rm -v $(pwd)/fluence_libvips.wasm:/code/code.wasm -p 30000:30000 fluencelabs/frun:latest
2019-10-07 18:25:46 info  run:	WasmVm: configs read...
2019-10-07 18:25:47 info  run:	WasmVm: scriptCtx prepared...
fluence.vm.VmError$InitializationError: Unable to initialize module=null
Caused by: asmble.run.jvm.RunErr$ImportNotFound: Cannot find compatible import for wasi_unstable::fd_close
	at asmble.run.jvm.ScriptContext.bindImport(ScriptContext.kt:287)
	at asmble.run.jvm.ScriptContext.bindImport(ScriptContext.kt:282)
	at asmble.run.jvm.ScriptContext.resolveImportFunc(ScriptContext.kt:299)
	at asmble.run.jvm.Module$Compiled.createInstance(Module.kt:123)
	at asmble.run.jvm.Module$Compiled.instance(Module.kt:70)
	at fluence.vm.wasm.module.WasmModule$.$anonfun$apply$1(WasmModule.scala:91)
	at scala.util.Try$.apply(Try.scala:213)
	at fluence.vm.utils$.safelyRunThrowable(utils.scala:35)
	at fluence.vm.wasm.module.WasmModule$.apply(WasmModule.scala:90)
	at fluence.vm.wasm.module.MainWasmModule$.apply(MainWasmModule.scala:149)
	at fluence.vm.WasmVm$.$anonfun$initializeModules$6(WasmVm.scala:203)
	at cats.instances.ListInstances$$anon$1.step$1(list.scala:116)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldM$2(list.scala:121)
	at cats.data.EitherTMonad.$anonfun$tailRecM$1(EitherT.scala:644)
	at cats.StackSafeMonad.tailRecM(StackSafeMonad.scala:15)
	at cats.StackSafeMonad.tailRecM$(StackSafeMonad.scala:15)
	at cats.effect.IOLowPriorityInstances$IOEffect.tailRecM(IO.scala:765)
	at cats.data.EitherTMonad.tailRecM(EitherT.scala:643)
	at cats.data.EitherTMonad.tailRecM$(EitherT.scala:640)
	at cats.data.EitherTInstances1$$anon$1.tailRecM(EitherT.scala:565)
	at cats.data.EitherTInstances1$$anon$1.tailRecM(EitherT.scala:565)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:121)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:12)
	at cats.Foldable.foldLeftM(Foldable.scala:285)
	at cats.Foldable.foldLeftM$(Foldable.scala:31)
	at cats.instances.ListInstances$$anon$1.foldLeftM(list.scala:12)
	at fluence.vm.WasmVm$.$anonfun$initializeModules$5(WasmVm.scala:197)
	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mikevoronov** [comment]
Hi!

Thank you for the issue, It is better to use [c-template](https://github.com/fluencelabs/c-template) for C projects and [cpp-template](https://github.com/fluencelabs/cpp-template) for C++ projects. I think that we will abandon this repo in favour of these templates.

**Comment by touhonoob** [comment]
@michaelvoronov works with WASI 6 after switching to the SDK from cpp-template. Thanks!
